### ISSUE TITLE
[bug] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libmetadata_god.so': dlopen failed: library "libmetadata_god.so" not found

### ISSUE THREAD

**Issue by zhangruiyu** [KRTirtho/metadata_god#22]
google  Pixel 4(android 12)

![image](https://github.com/KRTirtho/metadata_god/assets/10591822/19ea5812-2ce3-4057-abf6-10406c133946)

**Comment by KRTirtho** [comment]
Try `flutter clean`. May be it failed to download the shared libraries

**Comment by zhangruiyu** [comment]
> Try `flutter clean`. May be it failed to download the shared libraries

I tried. I still do

**Comment by zhangruiyu** [comment]
> I solved this by upgrade to 0.5.0, also remember to `flutter clean`

Thank you for your help😃
